server:
  port: 8080
  servlet:
    context-path: /member

spring:
  application:
    name: member
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://xxx:3306/fescar?useSSL=false&serverTimezone=UTC
#    username: xxx
#    password: xxx
#    druid:
#      max-active: 20
#      druid.min-idle: 2
#      druid.initial-size: 2

